name: Run bash script with Payload

on:
  push:
    branches:
      - main

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh command using ssh key
        uses: appleboy/ssh-action@v1.0.0
        env:
          SG_BASE_URL: "https://api.app.stackguardian.io"
          SG_API_TOKEN: 
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            whoami
            ls -la
            echo "SG_BASE_URL is ${{ vars.SG_BASE_URL }}"
