name: Run bash script with Payload

on:
  push:
    branches:
      - main

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    env: 
      PAYLOAD: sg-cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Bash Script
        run: |
          bash main.sh "$PAYLOAD"
